### ISSUE TITLE
Exporting as CoNLL results in a sentence per line

### ISSUE THREAD

**Issue by ktobah** [HumanSignal/label-studio#1250]
Hi,

I am planning to train a NER model (Chinese data), so I imported some tasks including predictions as a json format to label-studio. I finished checking and labeling them. Then, I chose to export my annotations as CoNLL format.

It ended up exporting the whole task text as the token per line, as follow: 

```
-DOCSTART- -X- O
标的车直行碰撞,本车(***,*****).可以正常行驶.物损1(三者)其他物损(护栏)受损,不需要赔偿.无需报警,非现场. -X- _ B-护栏

标的车直行碰撞,本车(***,*****).可以正常行驶.物损1(三者)其他物损(石墩)受损,不需要赔偿.已建议报警,非现场. -X- _ B-石墩
```

It is supposed to output one token per line. Any thoughts on why this is happening?

**Comment by ktobah** [comment]
I think I figured out the issue. It has to do with the fact that the label-studio converter expects the text to be in English (or Latin in general). So it uses the WhiteSpaceTokenizer() in [create_tokens_and_tags(text, spans)](https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/utils.py).

This won't work for Chinese. So is there a workaround?

**Comment by KonstantinKorotaev** [comment]
Hi @ktobah 
I have added this ticket to our backlog to fix this issue in one of the next releases. 
Meanwhile, you can use another tokenizer to fix this issue locally. For example, you can switch from WhiteSpaceTokenizer to [jieba] (https://pypi.org/project/jieba/).

**Comment by ktobah** [comment]
Hi @KonstantinKorotaev 

Thank you for doing that. Indeed, I fixed that by doing some text preprocessing using pkuseg tokenizer.

**Comment by KonstantinKorotaev** [comment]
Hi @ktobah 

Could you please share your code to help other people who have the same issue?

If you are willing to contribute to Label Studio - you can create a pull request with your changes.

**Comment by ktobah** [comment]
Hi @KonstantinKorotaev 

Sure, I can share the steps I followed. So, I took advantage of the fact that label-studio uses the WhiteSpaceTokenizer.

My end goal was to train a ner model using Spacy. The good thing is that Spacy already has a Chinese model that does tokenization. So, my first step was to take my text and tokenize it using Spacy as follow:

First make sure to install Spacy and the Chinese model (I used the large version because it is more accurate):

```
pip install -U spacy
python -m spacy download zh_core_web_lg
```

Then

```python
import spacy

# Load Chinese tokenizer, tagger, parser and NER
nlp = spacy.load("zh_core_web_lg")

# Process the document
text = "我爱北京天安门"
doc = nlp(text)

# This results in following tokens
# Tokens: ['我', '爱', '北京', '天安门']
```

Next step is simply to join these tokens back into a single string and add a space between them, so label-studio will be able to tokenize them correctly. This final string is the one that should be uploaded to label-studio.

```python
text = " ".join([token.text for token in doc])

# This give back
# text = "我 爱 北京 天安门"
```

That's it. I would say depending on the task that you want to achieve and the tool you want to use, first check the tokenizer used by that tool, then use the same tokenizer to get the same expected results. For instance, for the sake of explanation, if Spacy used jieba tokenizer only and I used pkuseg to tokenize, later when I want to use my texts for training I will run into a tokenization issue and I won't have the results I was expecting.
