### ISSUE TITLE
Failed to resolve reference '<ID>' to type 'User' 

### ISSUE THREAD

**Issue by piraka9011** [HumanSignal/label-studio#1381]
**Describe the bug**

I recently added a lot of users and their annotations using the API, however, when I tried to view the data in the project, I get a blank screen and the following error in the console:
```
Failed to resolve reference '77' to type 'User' (from node: /taskStore/list/24/annotators/0/user)
```
Where the error is repeated multiple times but the reference number is different.

**To Reproduce**
1. Create a user via the API
2. Get their token
3. Create a task and annotation using their token
4. Try to view the project and am greeted with a blank screen.

**Expected behavior**

The tasks should show up in LS.

**Screenshots**

![image](https://user-images.githubusercontent.com/16828657/131570053-7f353ee2-bb72-4bd3-9ec0-0cdb1102d6fd.png)

**Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - Label Studio Version: 1.2.0

**Comment by piraka9011** [comment]
I fixed this by manually assigning the users to the organization via the DB. 
It seems that the organization ID must be specified in order to avoid this error, despite the docs stating that it can be nullable.

This should be documented somewhere.

**Comment by makseq** [comment]
@smoreface
