### ISSUE TITLE
Filters applied twice in combination with bad transaction isolation lead to exponential growth of filters.

### ISSUE THREAD

**Issue by karelserruys-foodpairing** [HumanSignal/label-studio#1394]
**Describe the bug**
We're running Label Studio 1.0.2 with PostgreSQL 13 as database. 
When refreshing a project view, the frontend makes calls to the backend to reapply the all filters which are present on the view.
Additionally, the API is called once for each filter even though when using multiple filters, they need to be applied using a single API call.
Postgres's default transactional isolation is read committed. This in combination with transactions that add filters at almost the same moment, results in an exponential growth of filters eventually leading to an irresponsive application (because the amount of filters is to large to fetch from the backend).
When settings our Postgres to repeatable read partially solves the issue. Filters are no longer growing exponentially, because one of the simultaneous transactions fails. The problem is that the frontend keeps retrying both API calls until the moment the both succeed. This sometimes takes no more than a second, but sometimes it takes up to 30 seconds.

**To Reproduce**
1. Go to a project
2. Add a view
3. Add at least 2 filters
4. Refresh & watch the amount of calls that are being done to the backend adding filters

**Expected behavior**
Filters should only be added once.

**Screenshots**
Filters on the project view
![image](https://user-images.githubusercontent.com/79454108/131693329-c56d293b-0465-4e1a-aa60-efbe549c1da6.png)

Calls adding filters after first refresh
![image](https://user-images.githubusercontent.com/79454108/131693421-5699f2d4-73d2-43dd-83fe-e68555cdb62f.png)

Refresh again, resulting filters are:
![image](https://user-images.githubusercontent.com/79454108/131693805-66fc2d09-a814-4375-b90d-69fe4980d7af.png)

Calls when refreshing one more time:
![image](https://user-images.githubusercontent.com/79454108/131693889-4127f4f4-d7ab-4850-909a-f4506b815b0f.png)

Running locally with Postgres transaction isolation set to repeatable read
![image](https://user-images.githubusercontent.com/79454108/131692899-59d612cc-fd91-409b-b185-ec7885db6146.png)

**Environment (please complete the following information):**
 - OS: Screenshots were taking when running locally on my Windows machine. We also deployed label-studio to Cloud Run on GCP and there we have the same issue.
 - Label Studio Version 1.0.2
 - PostgreSQL 13

**Additional context**

**Comment by makseq** [comment]
@karelserruys-foodpairing Thank you for your report and ideas. We are working on this issue and we've decided to redesign all filter logic: we want to have an Apply button for filters and it solves this problem. Hope, it will be released soon.

**Comment by remoyson** [comment]
@makseq Any updates on this issue? Having the exact same problem with filters being applied multiple times and blocking application loading. Looking forward to a fix of this problem :)

**Comment by makseq** [comment]
@remoyson We have some fixes in the latest master, but not all. Could you check the latest commits?

**Comment by karelserruys-foodpairing** [comment]
@remoyson @makseq 
For me the issue was fixed when I upgraded to version 1.3.0.
I think the issue can be closed?
Regards
Karel
