### ISSUE TITLE
Can not import CSV data 

### ISSUE THREAD

**Issue by BruceStayHungry** [HumanSignal/label-studio#2356]
**Describe the bug**
When importing a CSV format data, I meet the following error: `django.http.request.RawPostDataException: You cannot access body after reading from request's data stream`
The whole error report:
![image](https://user-images.githubusercontent.com/40711748/168430788-7087f72b-761d-431f-a85f-f2ea5e8c033b.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Label Studio Version: 1.4.1 

**Additional context**
Here is a small size CSV file that can cause the error. How to solve the error? Deeply grateful for any help!
[questions.csv](https://github.com/heartexlabs/label-studio/files/8693203/questions.csv)

**Comment by makseq** [comment]
Your csv file works fine on my setup. 

Try to use python 3.8 and maybe another browser. We test it on google chrome.

**Comment by dvwright** [comment]
@BruceStayHungry try creating a Project then importing this file without changing any `Settings`

@makseq it looks like if any `Labeling Interface` has been specified this import fails.

**Comment by makseq** [comment]
As I remember if fields from the CSV are the same as from the Labeling Config, everything should work smoothly. 
If you could record a video, it would be very helpful.

**Comment by AkashDataScience** [comment]
If your file size is greater than 250MB, please refer this issue https://github.com/HumanSignal/label-studio/issues/4081.
