### ISSUE TITLE
Is it possible to create a template for a bbox for each class?

### ISSUE THREAD

**Issue by Surayuth** [HumanSignal/label-studio#2823]
I need to label multiple buttons having the same shape. I don't want to manually select a rectangle and draw a bbox every time as each bbox has the same shape. Is there a way to create a template for each bbox for each class?

**Comment by makseq** [comment]
@Surayuth What do you mean by "a template for each bbox"? do you have some visual examples?

**Comment by Surayuth** [comment]
@makseq Hello! Sorry for the late reply. Below is an example. I need to label each button. All of them have the same size. So, I want to know if I could just create a bbox with a specific size.

![1660500831](https://user-images.githubusercontent.com/66277085/185593795-20984889-a191-442b-8268-8253f88ae6b4.png)

**Comment by makseq** [comment]
@Surayuth Hello! You can use ctrl + c / ctrl + v for bboxes. Does it solve your problem?
