### ISSUE TITLE
Overlapping audio regions

### ISSUE THREAD

**Issue by makseq** [HumanSignal/label-studio#325]
I am trying to annotate "multilabel" audio regions (which is basically multi-label for my video segments); my problem is that after selecting region1, if region2 starts after region1 does, theres no way to label that overlap because instead it ends up _moving_  region1. I have added in an example screen recording when I tried to do this on the playground too, so I think this may not be a feature yet...but definitely a useful feature to have

It seems to work if region2 starts before region1 and continues into region1, though.
![thione](https://user-images.githubusercontent.com/12752337/84973411-db2e7900-b0d5-11ea-8d36-574d92801561.gif)

_Originally posted by @stalagmite7 in https://github.com/heartexlabs/label-studio/issues/296#issuecomment-645742387_

**Comment by makseq** [comment]
@stalagmite7 
Try to select the region using Results panel
![image](https://user-images.githubusercontent.com/501780/85077442-f0390400-b1ca-11ea-8c25-d97f2fb9f988.png)

**Comment by stalagmite7** [comment]
But its not about selecting region2, its about trying to _create_ region2 with a starting point that lies between region1's starting and ending point. To create region2, i have to move region1 out of the way after remembering its position, mark region 2, and move region1 back to its original position

**Comment by makseq** [comment]
@hlomzik it seems we need to note this

**Comment by hlomzik** [comment]
Oh, yes, this is important problem for audio/image regions, because we don't want to loose ability to move them easily, but it's necessary to create them in any place.
The good solution is to move regions only after selecting them. So any drag would create new region, because creating regions is more important than editing them.
I think that's better?

**Comment by jonorozcoc** [comment]
What about a lock button? Something like Photoshop or image editor layers. If you block a region you should be able to overlap new regions without move the blocked ones

**Comment by makseq** [comment]
@jonorozcoc In the last releases we added "eye" button to hide regions, it can be used as lock in some meaning.

**Comment by makseq** [comment]
Hope this behavior will be fixed with the Lock functionality and the new outlier panel.
