### ISSUE TITLE
Can existing brush areas be modified?

### ISSUE THREAD

**Issue by b-niu** [HumanSignal/label-studio#3257]
In tasks of image semantic segmentation annotations, if the existing brush area is not accurate enough, can I make corresponding modifications?

Sorry, I did not find corresponding content after reading the relevant documents.

![image](https://user-images.githubusercontent.com/32410912/202345702-94efa9d8-c04f-4e15-837b-fa683012a82b.png)

**Is your feature request related to a problem? Please describe.**
 Image semantic segmentation annotations. 
Correction of  inaccurate brush annotations in image.
Correction of inaccurate predictions.

**Describe the solution you'd like**
Select the brush, eraser and corresponding area to smear.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by yyassi-heartex** [comment]
Hi @b-niu, I hope all is well! 

You should be able to to make changes to a brush in 2 ways. both ways require that the brush region you want to be edit is selected (you can see if its selected if the region is highlighted in outliner or in the sidebar) if the region is not selected which can happen when switching to different tools, you can select the region using the Move tool (V) or by clicking on the desired region in outliner or sidebar. 
The 2 methods to edit 

1. Using the eraser tool and you have the desired brush region selected you should be able to remove the undesired areas
2. While the brush tool is selected you can select the the region from the outliner or sidebar then you should be able to continue drawing in the same region

I hope that helps :)

**Comment by yyassi-heartex** [comment]
Hi @b-niu thanks for the reproduction steps this is very useful! I'll create a ticket for this so we can address this as soon as possible!

thanks again!
