### ISSUE TITLE
Datetime displaying "March" as February

### ISSUE THREAD

**Issue by erikernst4** [HumanSignal/label-studio#3331]
**The bug**
Shows "March" as February

Using this code in the interface:
```
<View style="display: grid; ">
        <Text name="fields"/>
        <Choices name="fields_choice" toName="fields" showInLine="true" choice="multiple">
            <Choice value="Date"/>
        </Choices>
    </View>

    <View style="display: grid; " whenTagName="fields_choice" whenChoiceValue="Date" visibleWhen="choice-selected">
        <Header value="Date"/>
        <DateTime name="date" only="month,year" min="2020" max="2030"/>
```

**Screenshots**
![Screenshot from 2022-11-29 11-41-55](https://user-images.githubusercontent.com/65046031/204559229-77ceb455-dc87-47d4-9742-55d4ae83bfba.png)

**Environment:**
 - Label Studio Version 1.6.0

**Comment by hlomzik** [comment]
Hi! Thanks, that's a good catch! This happens on the last days of every month except February, because it tries to combine current day (like 31) and every month (like 31th of February) which leads to switch month and date on February. Fixed in LSF and will be merged soon.
