### ISSUE TITLE
Authorization Token collision with Google IAP (Identity-Aware Proxy)

### ISSUE THREAD

**Issue by mc-lp** [HumanSignal/label-studio#3349]
**Is your feature request related to a problem? Please describe.**
When Label Studio is deployed to Google Cloud Run with IAP (https://cloud.google.com/iap) active, I see a 302 redirect when I make an API call:

```
curl -X GET http://[MY_CLOUD_RUN_DOMAIN_NAME]/api/projects/ -H 'Authorization: Token <TOKEN>'
```

This is because Google's https://cloud.google.com/iap asks me to log in with my Google account first before I can hit the Label Studio API. 

I can bypass it by passing in a `GCP_IAAP_AUTH_TOKEN_[STRING]` cookie using Thunder Client or Postman, but I don't know of a way to pass a cookie to the Label Studio SDK (https://github.com/heartexlabs/label-studio-sdk) if I'm hitting Label Studio via another service/application.

**Describe the solution you'd like**
Three potential solutions:

1) Turn off Google IAP (this may not be feasible depending on product requirements)

2) Figure out a way to pass the `GCP_IAAP_AUTH_TOKEN_[STRING]` cookie to the Label Studio SDK (somehow??)

3) Fork and make a PR to the Label Studio repo so that it accepts `X-Api_Key` as an alternative to `Authorization: Token`. 

There's a possibility this third solution can be implemented via the third-party `djangorestframework-api-key` library at https://florimondmanca.github.io/djangorestframework-api-key/guide/#custom-header.

In other words, currently this is supported:
```
curl -X GET http://[MY_CLOUD_RUN_DOMAIN_NAME]/api/projects/ -H 'Authorization: Token <TOKEN>'
```
We want to be able to support the following as well:
```
curl -X GET http://[MY_CLOUD_RUN_DOMAIN_NAME]/api/projects/ -H 'X-Api-Key: <TOKEN>'
```

**Describe alternatives you've considered**
See above. This feature request focuses on the third solution. 

**Additional context**
1) Slightly related: GCP_IAAP_AUTH_TOKEN Cookies Without Suffix Ignored 
 https://issuetracker.google.com/issues/215575439?pli=1
 
2) The reason the https://florimondmanca.github.io/djangorestframework-api-key/guide/#custom-header looks like it might be a valid solution:

![image](https://user-images.githubusercontent.com/88687434/205146817-ae02cf4b-d264-4d75-8eca-d52beb3f740c.png)

**Comment by fstetic** [comment]
Any progress on this? We ran into the same problem with Label Studio on Azure. Custom header environment variable would be great.

**Comment by makseq** [comment]
Could you please try using this PR: 
https://github.com/HumanSignal/label-studio/pull/5555/files
