### ISSUE TITLE
Is there any template for annotating dataset for Coreference Resolution?

### ISSUE THREAD

**Issue by Tanmay98** [HumanSignal/label-studio#3493]
Hi, 
I tried annotating text in NER template and relation extraction template, my only problem is when I export data into json format I have the NER annotations as well as the relations but when I try exporting in the CoNLL format I lose the relations.

Is there any way I can get annotations for training a coref model? Thanks in advance.

**Comment by makseq** [comment]
Hi, do you have an example how CoNLL export should look like in this case?

**Comment by Tanmay98** [comment]
Hi, sure. 
This is the link to a CoNLL format [https://github.com/dbamman/litbank/blob/master/coref/conll/1023_bleak_house_brat.conll](url)
And this is the link to its raw text file [https://github.com/dbamman/litbank/blob/master/coref/tsv/1023_bleak_house_brat.txt](url)

**Comment by Tanmay98** [comment]
Also, I wrote a script to convert and it produced the CoNLL format file from the json input but spacy is giving me error on format still, although according to me it should have worked.
Let me know if you want to look at it !

**Comment by Tanmay98** [comment]
UPDATE: ACtually now that data is loaded perfectly using the script only

**Comment by makseq** [comment]
It would be awesome if you could contribute this script to our converter ;-)
