### ISSUE TITLE
Spacy Preloaded

### ISSUE THREAD

**Issue by getcontrol** [HumanSignal/label-studio#398]
This tool would be perfect if it included Spacy pre-annotations out of the box.

**Comment by normalnyi** [comment]
Hi, @getcontrol ! Could you give an example of spacy preannotations you mean?

**Comment by getcontrol** [comment]
Yes from https://spacy.io/api/annotation Models trained on the OntoNotes 5 corpus

**Comment by theudas** [comment]
I think you can do this fairly simple by using a ml backend which runs SpaCy like in this guide: https://labelstud.io/guide/ml.html and https://labelstud.io/tutorials/sklearn-text-classifier.html

**Comment by smoreface** [comment]
Please, check out this blog post @getcontrol 
https://labelstud.io/blog/Evaluating-Named-Entity-Recognition-parsers-with-spaCy-and-Label-Studio.html
