### ISSUE TITLE
Project page empty

### ISSUE THREAD

**Issue by xalebat** [HumanSignal/label-studio#6481]
![Immagine 2024-10-07 115051](https://github.com/user-attachments/assets/4bbcd791-820a-4470-83dd-c16d0d019e7f)

Hi! I opened a project I had already worked on and the page is completely blank. I cannot see the files nor my annotations. Can anyone please help me?

**Comment by blank0224** [comment]
Kindly try to open the project in Chrome but with not latest version. I faced the same issue today. 
It works in chrome (123.0.6312.86 (Official Build) (32-bit)). not worked in 129.0.6668.90 (Official Build) (32-bit)

**Comment by xalebat** [comment]
It worked, thanks!

 

Alessia BATTISTA

 

Da: blank0224 ***@***.***> 
Inviato: martedì 8 ottobre 2024 10:04
A: HumanSignal/label-studio ***@***.***>
Cc: xalebat ***@***.***>; Author ***@***.***>
Oggetto: Re: [HumanSignal/label-studio] Project page empty (Issue #6481)

 

Kindly try to open the project in Chrome but with not latest version. I faced the same issue today.
It works in chrome (123.0.6312.86 (Official Build) (32-bit)). not worked in 129.0.6668.90 (Official Build) (32-bit)

**Comment by austingg** [comment]
@blank0224 @xalebat what your label studio version？

**Comment by xalebat** [comment]
Hi, it’s 1.12.1. Older Chrome version works, as well as Mozilla Firefox

 

Da: Yubin Wang ***@***.***> 
Inviato: giovedì 10 ottobre 2024 11:12
A: HumanSignal/label-studio ***@***.***>
Cc: xalebat ***@***.***>; Mention ***@***.***>
Oggetto: Re: [HumanSignal/label-studio] Project page empty (Issue #6481)

 

@blank0224 <https://github.com/blank0224>  @xalebat <https://github.com/xalebat>  what your label studio version？

**Comment by makseq** [comment]
Please upgrade to the latest LS version - 1.13.1. 
Or downgrade your chrome browser before v128. Also, you can try firefox.
