### ISSUE TITLE
How to distinguish different project label result in redis?

### ISSUE THREAD

**Issue by thesby** [HumanSignal/label-studio#768]
I use the redis to store label result, but I find that the keys are just `id`. And I cannot split them into different project. How to deal with this? I set the `path` as `label_result`, but there is nothing about `label_result`.

**Comment by thesby** [comment]
@makseq I think add a prefix is really useful.

**Comment by makseq** [comment]
I think we need to add a data manager column with storage name or something like this..

**Comment by makseq** [comment]
Now we have `storage filename` column:

![image](https://github.com/user-attachments/assets/7fe8e798-d9b8-4cbc-a5aa-5c1cb926cd6f)
