### ISSUE TITLE
Label studio cannot export images with zero bounding box annotations because 'original_width' and 'original_height' are stored inside 'result' key

### ISSUE THREAD

**Issue by Lauler** [HumanSignal/label-studio#921]
**Describe the bug**
Currently `original_width` and `original_height` will disappear if a user submits a task with zero bounding box annotations. This is because they are stored inside of the `["result"]` key. No elements exist inside of `["result"]` key if a user submits an annotation with zero bounding box annotations. 

The issue this produces is that Label Studio silently ignores exporting annotations with zero bounding boxes when a user clicks export to COCO/PASCAL/YOLO. I.e. if 100 images are submitted as finished tasks, and 10 of them have zero bounding boxes, then Label Studio export to COCO/PASCAL/YOLO will only export the 90 observations which have bounding box annotations. 

**To Reproduce**
1. Start a project with standard object detection labeling interface.
2. Import two images (any images will do fine).
3. Make a bounding box annotation for one of the images and submit task. For the other image submit task with zero bounding box annotations.
4. Export as COCO/PASCAL. Only 1 image will be exported in both `.json` file and `images/` folder.

**Expected behavior**
All submitted tasks should be exported in the COCO/PASCAL output. Submitted tasks with zero bounding boxes should also be exported but with `bbox: []` .

**Environment (please complete the following information):**
 - Ubuntu 20.04
 - Label Studio Version 1.0.1

**Additional context**
If possible `original_width` and `original_height` should ideally be saved on the image level (inside of `["annotations"][0]` and `["predictions"][0]`. This way information about image dimensions will not disappear if users submit tasks with zero bounding box annotations.

**Comment by makseq** [comment]
Thank you for your report. Yes, LS reads images only in user's browsers while labeling. Data is not always accessible on the LS server side, so LS can't read image sizes while converting.

**Comment by jrdalenberg** [comment]
I can imagine that you are super busy, but is there perhaps any ETA on when this could be resolved? 

Or do you perhaps have pointers in which files we would should to fix this to make a PR?

**Comment by makseq** [comment]
This is not a critical bug, it seems more like improvement. Closed as outdated and not a popular request.
